### ISSUE TITLE
Sprint Plan for October 15 - 19, 2018

### ISSUE THREAD

**Issue by Mloweedgar** [CodeTanzania/emis-docs#155]
### Description
This plan captures our tasks for October 15 - 19, 2018. This is a 4-days sprint.
Tasks below will be accomplished at the end of this sprint:

### API(s) (@lykmapipo )
- [ ] Provide initial feature API :link:CodeTanzania/emis-feature#2
- [ ] Provide initial assessment API :link:CodeTanzania/emis-rat#1
- [ ] Provide initial incidents API :link:CodeTanzania/emis-incident#1
- [x] Provide initial plan API :link:CodeTanzania/emis-plan#2
- [x] Improve alerts API make it return  polygons with centro-id coordinates :link: CodeTanzania/emis-alert#18

### Alerts (@Mloweedgar  )
- [x] Display all alerts on map using marker Icons :link:  CodeTanzania/emis-web-alert#24
- [x] Display alert details when marker icon is clicked :link: CodeTanzania/emis-web-alert#25, :link: CodeTanzania/emis-web-alert#16, :link: CodeTanzania/emis-web-alert#15, :link: CodeTanzania/emis-web-alert#30
- [x] Color alert polygons based on urgency level :link: CodeTanzania/emis-web-alert#18
- [ ] Display alert marker icons based on alert's category :link: CodeTanzania/emis-web-alert#17

### Plans (@BenMaruchu   )
- [x] Implement form for creating plan  :link: codetanzania/emis-dashboard#93
- [x] Implement  form for creating activities :link: codetanzania/emis-dashboard#94
- [x] Implement form creating SOP/Tasks :link: codetanzania/emis-dashboard#95
- [ ] Implement breadcrumbs to enable back navigation. :link: codetanzania/emis-dashboard#69

### Settings (@mkumbobeaty    )
- [x]  Improve font size in settings :link: codetanzania/emis-dashboard#92
- [x]  Implement search functionality :link: codetanzania/emis-dashboard#96
- [ ] Improve responsiveness :link: codetanzania/emis-dashboard#97

### Project Documentation and UI/UX improvements (@navish )
- [x]  Improve on Front-end contribution guide :link: codetanzania/emis-dashboard#83
- [ ] Improve Alert UI design
- [ ] Contact UI Designer

### Incidents (@kasongoyo  )
- [x] Improve test coverage in stakeholder
- [x] Upgrade the project create react app script to version 2.0.3
- [ ]  Implement Incident view Layout
- [ ]  Add new incident form

**Comment by lykmapipo** [comment]
@Mloweedgar Please check latest alert API. Its not use TMA Alerts but now all alerts will have a centroid in their area. 

```js
{
  ...
  area:
  {
    description: "Tandale",
    geometry:
    {
      type: "Polygon",
      coordinates: [...]
    },
    centroid:
    {
      type: "Point",
      coordinates: [
        30.96055978906844,
        -3.1747108710154697
      ]
    },
    altitude: 7143,
    ceiling: 53687
  }
}
```

**Comment by Mloweedgar** [comment]
@lykmapipo I hope remember the scenario. the points will correspond to the number of regions affected by the Alert.

**Comment by Mloweedgar** [comment]
Also @lykmapipo can you create a specific issue concerning this so as we can continue with this conversation. I think you can use the JSON of TMA Alerts I shared let us discuss this further.

**Comment by BenMaruchu** [comment]
I'm closing this issue... It's timeline is over.
