### ISSUE TITLE
Sprint Plan for October 22 - 26, 2018

### ISSUE THREAD

**Issue by Mloweedgar** [CodeTanzania/emis-docs#156]
### Description
This Iteration plan captures our tasks for October - November, 2018. 

### API(s) (@lykmapipo )
- [x] Refactor emis-asat to stakeholder
- [ ] Simplify emis-alert API
- [x] Review and improve initial emis components API
- [ ] Publish emis-api with all API in place
- [ ] Trace API to cover EMIS scenario(contract) end to end

### Alerts (@Mloweedgar  )
- [x] Improve Alert details UI :link: CodeTanzania/emis-web-alert#33
- [ ] Implement Notify Stakeholder UI :link: CodeTanzania/emis-web-alert#34
- [x] Visit EOC
- [ ] Visit TMA

### Plans (@BenMaruchu   )
- [x] Wire plan UI with the API
- [x] Wire Activities UI with API
- [ ] Wire SOP UI with API
- [ ] Allow Plan, Activity and SOP creation
- [x] Setup redux thunk :link: codetanzania/emis-dashboard#101
- [x] Setup axios as http library :link: codetanzania/emis-dashboard@81e8eaa3ee580af88d2689ff52ecd20f9a173e84

### Stakeholders (@kasongoyo  )
- [ ] ...
- [ ] ...

**Comment by lykmapipo** [comment]
Why not `Sprint Plan for October 22 - 26, 2018`

**Comment by BenMaruchu** [comment]
This issue has expired.
