### ISSUE TITLE
Sprint Plan for October - November 29 - 02, 2018

### ISSUE THREAD

**Issue by Mloweedgar** [CodeTanzania/emis-docs#159]
### Description
This Iteration plan captures our tasks for October - November, 2018. 

### API(s) (@lykmapipo )
- [ ]  Simplify and Refactor Alert API and seed TMA data :link: CodeTanzania/emis-alert#4 :link: CodeTanzania/emis-alert#5 :link: CodeTanzania/emis-alert#8 :link: CodeTanzania/emis-alert#4 :link: CodeTanzania/emis-alert#9 :link: CodeTanzania/emis-alert#10 :link: CodeTanzania/emis-alert#13 :link: CodeTanzania/emis-alert#14 :link: CodeTanzania/emis-alert#20 
- [x]  Improve and Refactor Incident Type API and add its domain model :link: CodeTanzania/emis-incident-type#4 :link: CodeTanzania/emis-incident-type#5 :link: CodeTanzania/emis-incident-type#6 :link: CodeTanzania/emis-incident-type#7 :link: CodeTanzania/emis-incident-type#8
- [ ]  Wire email and sms notifications to stakeholder on both alert and stakeholder API :link: CodeTanzania/emis-stakeholder#7 :link: CodeTanzania/emis-stakeholder#12
- [ ]  Deploy single API endpoint for EMIS

### Alerts (@Mloweedgar  )
- [ ]  visiting TMA
- [ ] Notify feature  :link: CodeTanzania/emis-web-alert#34
- [ ]  Display Incident type Icons based on Alerts  :link: CodeTanzania/emis-web-alert#17

### Plans (@BenMaruchu   )
- [x]  wire up SOP
- [ ] Create Plan, Activities and SOP
- [ ]  Multi-language support

### Stakeholders (@kasongoyo  )
- [ ]  Aligning with new API(update on API)
- [ ]  Implement notification feature(UI)

**Comment by BenMaruchu** [comment]
It's time has passed
